### ISSUE TITLE
Server or Code?

### ISSUE THREAD

**Issue by gordsellar** [nhr/swn#14]
Hi there, 

I noticed this is down over at the site where you're hosting it:

http://swn.emichron.com/

![Screen Shot 2020-01-12 at 3 36 53 PM](https://user-images.githubusercontent.com/17806430/72215069-70d74280-3551-11ea-8e02-545f9cbfb6b2.png)

Is that an issue just on your server, or is there something wrong in the code?

(Also, did you ever manage to update it for the Revised Edition?)

**Comment by gordsellar** [comment]
PS: I'd volunteer to help, but can't really code to save my life. :(

**Comment by nhr** [comment]
Thanks for bringing this to my attention! I’ll dig into it in a few hours.

**Comment by ghost** [comment]
This is still an issue, @nhr . Anything we can do to help out?

**Comment by nhr** [comment]
The problem is that the current version of Perl on the web host is 5.30.1, but the DBI Perl module on the host was built against a previous version of Perl, as suggested by the first line of this error log dump:

```
[Tue Feb 25 21:51:48.841737 2020] [cgid:error] [pid 56224:tid 139978495461120] [client 108.49.197.43:33846] Can't load '/usr/local/lib64/perl5/auto/DBI/DBI.so' for module DBI: libperl.so.5.28: cannot open shared object file: No such file or directory at /usr/lib64/perl5/DynaLoader.pm line 193.: /var/www/swn.emichron.com/html/CGI/sectorgen.cgi, referer: http://swn.emichron.com/
[Tue Feb 25 21:51:48.842053 2020] [cgid:error] [pid 56224:tid 139978495461120] [client 108.49.197.43:33846] : /var/www/swn.emichron.com/html/CGI/sectorgen.cgi, referer: http://swn.emichron.com/
[Tue Feb 25 21:51:48.842228 2020] [cgid:error] [pid 56224:tid 139978495461120] [client 108.49.197.43:33846] BEGIN failed--compilation aborted at /usr/local/lib64/perl5/DBI.pm line 284.: /var/www/swn.emichron.com/html/CGI/sectorgen.cgi, referer: http://swn.emichron.com/
[Tue Feb 25 21:51:48.842399 2020] [cgid:error] [pid 56224:tid 139978495461120] [client 108.49.197.43:33846] Compilation failed in require at /var/www/swn.emichron.com/html/CGI/sectorgen.cgi line 14.: /var/www/swn.emichron.com/html/CGI/sectorgen.cgi, referer: http://swn.emichron.com/
[Tue Feb 25 21:51:48.842553 2020] [cgid:error] [pid 56224:tid 139978495461120] [client 108.49.197.43:33846] BEGIN failed--compilation aborted at /var/www/swn.emichron.com/html/CGI/sectorgen.cgi line 14.: /var/www/swn.emichron.com/html/CGI/sectorgen.cgi, referer: http://swn.emichron.com/
[Tue Feb 25 21:51:48.844024 2020] [cgid:error] [pid 56224:tid 139978495461120] [client 108.49.197.43:33846] End of script output before headers: sectorgen.cgi, referer: http://swn.emichron.com/
```
I tried rebuilding the DBI module with cpanm, and while that appears to work, I still get the same error as above, even after restarting the httpd service.

So, I'm definitely open to suggestions!

**Comment by ghost** [comment]
I haven't had experience with production perl in a long time, so not sure if I can help out in that regard.

**Comment by nhr** [comment]
The site should be back up now. I have moved the site off of bare metal and onto a Linux container hosting system. Nice side benefit: swn.emichron.com is now secured using Let's Encrypt.

So, [give it a shot](https://swn.emichron.com/) and let me know if it is working for you.

**Comment by nhr** [comment]
It looks like there's been a fair amount of activity on the site since I deployed it on the new platform. I'm going to consider this issue resolved. Please feel free to comment if you see any other errors.
