### ISSUE TITLE
NPCs - add Problems, Job Motivation and Noticeable Quirks

### ISSUE THREAD

**Issue by ScottMaclure** [nhr/swn#4]
As per p232 of SWN.

I'd find it useful for ideas if those were already rolled for me.

**Comment by nhr** [comment]
Hey @ScottMaclure - thanks for the feedback! This information is actually generated and included in the resulting GM's TiddlyWiki file. You just need to drill into a given NPC to see these details. Does this satisfy your request?

![screen shot 2017-01-03 at 14 39 06](https://cloud.githubusercontent.com/assets/1874097/21620464/7586f88e-d1c2-11e6-9421-e270a390dab1.png)

**Comment by ScottMaclure** [comment]
Wow! That's great. Cheers.
